version: '3.7'
services:
  postgres:
    image: postgres:12.2
    container_name: my-db
    ports:
    - 5432:5432
#    volumes:
#	- postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=parool
    networks:
    - pg_net
  pgadmin4:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin4
    ports:
    - 8080:80
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=user@domain.com
    - PGADMIN_DEFAULT_PASSWORD=Secret
    networks:
    - pg_net
networks:
  pg_net:
volumes:
#  postgres-data:
  pgadmin-data:
